#!/usr/bin/python3

import sys, getopt, os
from sammcheck import SAMMWorker
import time
import logging
import signal
from threading import Timer
import configparser

w = None
keep_running = True

config = configparser.ConfigParser()

config['DEFAULT']['job_wait'] = '5'
config['DEFAULT']['retry_delay'] = '5'
config['DEFAULT']['stats_time'] = '5'
config['DEFAULT']['config_file'] = "/usr/local/nagios/etc/sammworker/sammworker.cfg"
config['DEFAULT']['pid_file'] = "/run/sammworker_process.pid"
config['DEFAULT']['qh_file'] = "/usr/local/nagios/var/rw/nagios.qh"
config['DEFAULT']['debug'] = '0'
config['DEFAULT']['log_file'] = "/usr/local/nagios/var/sammworker.log"
config['DEFAULT']['plugin_name'] = "check_sammworker"

def sig(signum, frame):
    global w, keep_running, config

    w.close()
    if signum == signal.SIGINT:
        logging.warning('Interrupt received. Closing connections')
        keep_running = False
        os.remove(config['DEFAULT']['pid_file'])
        logging.shutdown()
    elif signum == signal.SIGHUP:
        logging.warning('Restarting the conneciton')
        w.connect()
        w.register()
    else:
        logging.warning('Signal handler called with signal %s' % str(signum))

def help(msg=""):
    print("%s\n" \
        "USAGE: %s [ options ]\n" \
        "-c <config file>  Config file (mandatory)\n" \
        "-F                Run in the foreground\n" \
        "-r <seconds>      Delay between attempts of connection to worker pipe in seconds (def: 5 seconds)\n" \
        "-j <seconds>      Time to wait for jobs in seconds (def: 5 seconds)\n" \
        "-p <pid file>     Path to the PID file (def: /run/sammworker_process.pid)\n" \
        "-u <username>     Username to run this process (def: nagios)\n" \
        "-d <level>        Debug level\n" \
        "-h                Print this screen" % \
        (msg, sys.argv[0]))
    return -1

def main(argv):
    t = None
    global keep_running, w, config
    override = {}
    config_file = None

    try:
        opts, args = getopt.getopt(argv, "Fr:j:p:d:c:")
    except getopt.GetoptError:
        return help()

    foreground=False
    for opt, arg in opts:
        if opt == '-h':
            return help()
        elif opt == '-F':
            foreground = True
        elif opt == '-r':
            override['retry_delay'] = arg
        elif opt == '-j':
            override['job_wait'] = arg
        elif opt == '-p':
            override['pid_file'] = arg
        elif opt == '-d':
            override['debug'] = arg
        elif opt == '-c':
            config_file = arg
        else:
            return help("Invalid parameter %s" % arg)

    if config_file is None:
        return help("Parameter config_file is mandatory")

    config.read(config_file)
    for k in override.keys():
        config['DEFAULT'][k] = override[k]

    if config['DEFAULT'].getint('debug') > 0:
        logging.basicConfig(level=logging.DEBUG, filename=config['DEFAULT']['log_file'])
    else:
        logging.basicConfig(level=logging.INFO, filename=config['DEFAULT']['log_file'])

    if foreground == False:
        n = os.fork()
        if n > 0:
            return 0

    with open(config['DEFAULT']['pid_file'], "w") as f:
        pid = os.getpid()
        f.write(str(pid))

    signal.signal(signal.SIGHUP, sig)
    signal.signal(signal.SIGINT, sig)

    while keep_running:
        w = SAMMWorker(config['DEFAULT']['plugin_name'], wait=config['DEFAULT'].getint('job_wait'), address=config['DEFAULT']['qh_file'])
        while w.connected == False:
            try:
                w.connect()
                logging.info("Connected to Nagios. Starting to process requests")
            except Exception as e:
                logging.warning("Nagios not running. Retrying in 5 seconds. %s" % str(e))
                time.sleep(config['DEFAULT'].getint('retry_delay'))
        w.register()
        if w.registered:
            logging.info("Registered")
        else:
            logging.critical("Unable to register. Aborting")
            w.close()
        while keep_running and w.registered and w.connected:
            if t is None or time.time() - t > config['DEFAULT'].getint('stats_time'):
                logging.info(w.stats())
                t = time.time()
            try:
                if w.recv():
                    logging.debug("Received data.")
                else:
                    logging.debug("No data received. Check jobs.")
            except Exception as e:
                logging.warning("Unable to receive data. Exiting loop. %s" % str(e))
                continue
            for j in w.jobs:
                if w.run(j):
                    logging.debug("Ran job %s" % j)
            for j in w.jobs:
                if w.done(j):
                    logging.debug("Finished job %s" % j)
        logging.warning("Disconnected from Nagios.")
        w.close()
    os.remove(config['DEFAULT']['pid_file'])
    return 0

if __name__ == "__main__":
    exit(main(sys.argv[1:]))
